services:
  web:
    build:
      context: ../.. # Root of the monorepo
      dockerfile: apps/auth-frontend/Dockerfile.frontend.prod
    container_name: web
    ports:
      - '3000:3000'
    volumes:
      - ../../.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
