name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy backend to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-backend-production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --config ./apps/auth-backend/fly.toml --dockerfile ./apps/auth-backend/Dockerfile.prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
