name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'apps/auth-frontend/**' # Only deploy frontend if there are changes to the frontend app code
      - 'packages/**' # Or deploy frontend if there are changes to the shared packages
      - '.github/workflows/**' # Or deploy frontend if there are changes to the GitHub workflow files

jobs:
  deploy:
    name: Deploy frontend to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-frontend-production
    
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm build:shared
      - name: Build frontend
        working-directory: apps/auth-frontend
        run: pnpm run build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a auth-frontend --remote-only --config ./apps/auth-frontend/fly.toml --dockerfile ./apps/auth-frontend/Dockerfile.frontend.prod --build-secret VITE_BASE_API_URL=https://auth-backend-blue-darkness-6417.fly.dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_FRONTEND_TOKEN }}
